name: Build ARM64 Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Download Release JAR
        run: |
          mkdir -p ./build
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -o ./build/datatool-1.0-SNAPSHOT.jar \
            $(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/v20250930 \
            | grep "browser_download_url.*datatool-1.0-SNAPSHOT.jar" \
            | cut -d '"' -f 4)

      - name: Build ARM64 Docker image and export tar
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t datatool:${GITHUB_RUN_NUMBER} \
            --output type=tar,dest=./datatool-arm64.tar \
            .

      - uses: actions/upload-artifact@v4
        with:
          name: datatool-arm64
          path: ./datatool-arm64.tar
