name: Build ARM64 Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Download Release JAR
        uses: snok/install-gh-release@v0.7.0
        with:
          owner: ${{ github.repository_owner }}
          repo: datatool
          tag: v20250930
          asset: datatool-1.0-SNAPSHOT.jar
          output: ./build

      - name: Build ARM64 Docker image and export tar
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t datatool:${GITHUB_RUN_NUMBER} \
            --output type=tar,dest=./datatool-arm64.tar \
            .

      - uses: actions/upload-artifact@v4
        with:
          name: datatool-arm64
          path: ./datatool-arm64.tar
