name: Build ARM64 Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 QEMU 模拟器以支持跨平台构建
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 下载 Release JAR
      - name: Download Release JAR
        run: |
          mkdir -p ./build
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           -o ./build/datatool-1.0-SNAPSHOT.jar \
           https://github.com/Wenny990/datatool/releases/download/v20250930/datatool-1.0-SNAPSHOT.jar

      # 5. 构建 ARM64 Docker 镜像并导出 tar
      - name: Build ARM64 Docker image and export tar
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t datatool:${GITHUB_RUN_NUMBER} \
            --output type=tar,dest=./datatool-arm64.tar \
            .

      # 6. 上传 tar 作为 artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: datatool-arm64
          path: ./datatool-arm64.tar
