name: Build ARM64 Docker Image

on:
  workflow_dispatch:   # 手动触发
  push:
    tags:
      - 'v*'           # 当 push 以 v 开头的 tag 时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Download Release JAR
      uses: actions/download-release@v2
      with:
        repository: ${{ github.repository }}
        tag: v20250930        # 对应你的 Release tag
        asset_name: datatool-1.0-SNAPSHOT.jar
        path: ./build         # 下载到 build 目录

    - name: Build ARM64 Docker image and export tar
      run: |
        docker buildx build \
          --platform linux/arm64 \
          -t datatool:${GITHUB_RUN_NUMBER} \
          --output type=tar,dest=./datatool-arm64.tar \
          .
          
    - name: Upload tar as artifact
      uses: actions/upload-artifact@v4
      with:
        name: datatool-arm64
        path: ./datatool-arm64.tar
